clearvars

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%plot comparisons generated by compare_AC_iagos
%
%Corwin Wright, c.wright@bath.ac.uk, 2020/05/19
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% settings
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Settings.InFile = 'comparison.mat';


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% prep
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


Data = load(Settings.InFile);

Vars = Data.Settings.Vars;
Grid = Data.Settings.Grid.TPrime;
Data = Data.Results;

Range = [log10(10) log10(10000)];%max(log10(Data(:)))];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% plot!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clf
set(gcf,'color','w')
Letters = 'abc';
subplot = @(m,n,p) subtightplot (m, n, p, 0.04, 0.2, 0.2);

for iCompare = 1:1:numel(Vars)-1
  
  %prepare panel
  subplot(1,3,iCompare)
  cla
  hold on
  
  %get data
  ToPlot  = log10(squeeze(Data(:,:,iCompare)));
  VarName = Vars{iCompare+1};

  %plot data  
  pcolor(Grid,Grid,ToPlot)
  
  %grid lines
  for iX=min(Grid):2:max(Grid);
    plot([1,1].*iX,[min(Grid),max(Grid)],':','linewi',0.5,'color',[1,1,1].*0.6)
    plot([min(Grid),max(Grid)],[1,1].*iX,':','linewi',0.5,'color',[1,1,1].*0.6)    
  end
  plot([min(Grid),max(Grid)],[1,1].*max(Grid),'k-')
  plot([min(Grid),max(Grid)],[1,1].*min(Grid),'k-')  
  plot([1,1].*min(Grid),[min(Grid),max(Grid)],'k-')   
  plot([1,1].*max(Grid),[min(Grid),max(Grid)],'k-')   
  plot([0,0],[min(Grid),max(Grid)],'k-')
  plot([min(Grid),max(Grid)],[0,0],'k-')  
  
  %1:1 line
  plot(Grid,Grid,'k:','linewi',0.25)
  
  %tidy
  axis([-1 1 -1 1].*max(Grid(:)))
  axis square  
  shading flat
  set(gca,'xtick',min(Grid):2:max(Grid),'ytick',min(Grid):2:max(Grid))
  
  %colours
  caxis(Range)
  colormap(cbrew('Reds',16));
  
  %x-axis label
  xlabel([VarName,' [K]'], 'Interpreter', 'none')
  if iCompare == 1;  end
  
  %y-axis and y-axis labels
  switch iCompare
    case 1;    set(gca,'yaxislocation', 'left'); ylabel(['air_temp_AC [K]'], 'Interpreter', 'none');
    case 3;    set(gca,'yaxislocation','right'); ylabel(['air_temp_AC [K]'], 'Interpreter', 'none');
    otherwise; set(gca,'ytick',[]);
  end
  
  %title
  switch VarName
    case 'air_stag_temp_AC'; VarName = 'Aircraft stagnation';
    case 'air_stag_temp_PM'; VarName = 'MOZAIC stagnation';
    case 'air_temp_PM';      VarName = 'MOZAIC';
  end
  title(['(',Letters(iCompare),') ',VarName])
  
  %linear fit and correlation
  x = [];
  y = [];
  for iX = 1:1:numel(Grid)
    for iY = 1:1:numel(Grid)
      x = cat(1,x,ones(Data(iX,iY,iCompare),1).*Grid(iX));
      y = cat(1,y,ones(Data(iX,iY,iCompare),1).*Grid(iY));      
    end
  end
  clear iX iY
  r = corrcoef(x,y); r = r(2);
  p = polyfit(y,x,1);
  text(Grid(5),Grid(end-10),['r = ',num2str(round(r.*100)./100)],'fontsize',12)
  text(Grid(5),Grid(end-30),['y = ',num2str(round(p(1).*100)./100),'x + ',num2str(round(p(2).*100)./100)],'fontsize',12)
  plot(Grid,polyval(p,Grid),'k--')

  %done
  drawnow

end; clear iCompare

%colour bar
cb = colorbar('position',[0.87,0.35,0.01,0.3],'ytick',1:1:4,'yticklabel',10.^(1:1:4));
cb.Label.String = ['Number of points'];